name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SNAKEMAKE_OUTPUT_CACHE: snakemake_cache

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    needs:
      - Formatting
      - Linting
    steps: 
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Snakemake cache
      id: cache-sm
      uses: actions/cache@v3
      with:
        path: ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        key: ${{ runner.os }}-sm
    - name: Install Mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        python-version: 3.9
        channels: conda-forge,bioconda,nodefaults
        channel-priority: strict
    - name: Install Snakemake
      run: mamba env create -f environment.yml
    - name: Run workflow
      run: |
        mkdir -p ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        export SNAKEMAKE_OUTPUT_CACHE=${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        snakemake all --use-conda --cache --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --all-temp --configfile .test/config.yml
